clean_mtl_eng <- function(mtl_eng_raw){
  
  # clean column names 
  mtl_eng_cols <- clean_names(mtl_eng_raw)
  
  # rename columns
  mtl_eng_rcols <- mtl_eng_cols %>% 
    rename(eighteen = are_you_over_18_years_old,
           municipality = in_which_city_boundary_or_municipality_do_you_live_in_please_select_the_municipality_not_the_neighbourhood_or_region,
           importance_largeoldtrees = how_important_to_you_are_each_of_the_following_things_about_these_trees_large_old_trees,
           importance_historystories = how_important_to_you_are_each_of_the_following_things_about_these_trees_a_place_for_human_history_and_stories,
           importance_stressrelief = how_important_to_you_are_each_of_the_following_things_about_these_trees_getting_away_from_stresses_of_everyday_life,
           importance_walks = how_important_to_you_are_each_of_the_following_things_about_these_trees_a_place_for_a_short_walk,
           importance_culturaltraditions = how_important_to_you_are_each_of_the_following_things_about_these_trees_learning_about_cultural_traditions,
           importance_accessiblespace = how_important_to_you_are_each_of_the_following_things_about_these_trees_a_place_that_is_accessible_for_everybody,
           importance_cleanairwatercity = how_important_to_you_are_each_of_the_following_things_about_these_trees_clean_air_clean_water_and_healthy_cities,
           importance_nativespecies = how_important_to_you_are_each_of_the_following_things_about_these_trees_many_kinds_of_native_animals_birds_and_plants,
           importance_welcoming = how_important_to_you_are_each_of_the_following_things_about_these_trees_make_the_city_more_welcoming,
           importance_liveability = how_important_to_you_are_each_of_the_following_things_about_these_trees_a_more_liveable_city,
           importance_socializing = how_important_to_you_are_each_of_the_following_things_about_these_trees_spaces_for_people_to_interact_and_socialise,
           importance_communitycohesion = how_important_to_you_are_each_of_the_following_things_about_these_trees_improving_community_cohesion,
           importance_beauty = how_important_to_you_are_each_of_the_following_things_about_these_trees_beautiful_sights_sounds_and_smells,
           importance_cleanenvsupportingppl = how_important_to_you_are_each_of_the_following_things_about_these_trees_a_healthy_environment_that_supports_human_life,
           importance_attractingpeople = how_important_to_you_are_each_of_the_following_things_about_these_trees_attracting_tourists_and_residents_to_the_city,
           importance_maintainculture = how_important_to_you_are_each_of_the_following_things_about_these_trees_maintain_indigenous_or_european_cultures,
           agree_allergies = how_much_do_you_agree_that_the_trees_in_your_city_or_neighbourhood_cause_allergies,
           agree_blockroadsigns = how_much_do_you_agree_that_the_trees_in_your_city_or_neighbourhood_block_the_visibility_of_road_signs,
           agree_damageproperty = how_much_do_you_agree_that_the_trees_in_your_city_or_neighbourhood_damage_property_including_concrete_paths_and_powerlines,
           agree_messy = how_much_do_you_agree_that_the_trees_in_your_city_or_neighbourhood_create_mess,
           agree_ugly = how_much_do_you_agree_that_the_trees_in_your_city_or_neighbourhood_are_ugly,
           agree_toomuchwater = how_much_do_you_agree_that_the_trees_in_your_city_or_neighbourhood_use_too_much_water,
           agree_blockpipes = how_much_do_you_agree_that_the_trees_in_your_city_or_neighbourhood_block_water_pipes_and_drains,
           agree_blocksun = how_much_do_you_agree_that_the_trees_in_your_city_or_neighbourhood_block_the_sun,
           agree_expensive = how_much_do_you_agree_that_the_trees_in_your_city_or_neighbourhood_are_expensive_to_maintain,
           agree_dropbranches = how_much_do_you_agree_that_the_trees_in_your_city_or_neighbourhood_drop_branches,
           agree_toomuchspace = how_much_do_you_agree_that_the_trees_in_your_city_or_neighbourhood_take_up_too_much_space,
           agree_wildfires = how_much_do_you_agree_that_the_trees_in_your_city_or_neighbourhood_promote_wildfires,
           agree_undesirableanimals = how_much_do_you_agree_that_the_trees_in_your_city_or_neighbourhood_attract_undesirable_animals,
           agree_desirableanimals = how_much_do_you_agree_that_the_trees_in_your_city_or_neighbourhood_attract_desirable_animals,
           agree_screenbadviews = how_much_do_you_agree_that_the_trees_in_your_city_or_neighbourhood_screen_unattractive_views,
           agree_createsafety = how_much_do_you_agree_that_the_trees_in_your_city_or_neighbourhood_make_streets_and_parks_safer,
           agree_calming = how_much_do_you_agree_that_the_trees_in_your_city_or_neighbourhood_are_calming,
           agree_cleanair = how_much_do_you_agree_that_the_trees_in_your_city_or_neighbourhood_clean_the_air,
           agree_provideshade = how_much_do_you_agree_that_the_trees_in_your_city_or_neighbourhood_provide_shade,
           agree_produceoxygen = how_much_do_you_agree_that_the_trees_in_your_city_or_neighbourhood_produce_oxygen,
           agree_cooling = how_much_do_you_agree_that_the_trees_in_your_city_or_neighbourhood_cool_the_neighborhood,
           agree_reducefloods = how_much_do_you_agree_that_the_trees_in_your_city_or_neighbourhood_reduce_flooding,
           agree_goodexercise = how_much_do_you_agree_that_the_trees_in_your_city_or_neighbourhood_make_a_place_good_for_exercise_walk_run_cycle,
           agree_goodshopping = how_much_do_you_agree_that_the_trees_in_your_city_or_neighbourhood_make_a_place_good_for_shopping,
           agree_incpropertyvalues = how_much_do_you_agree_that_the_trees_in_your_city_or_neighbourhood_increase_property_values,
           agree_spiritual = how_much_do_you_agree_that_the_trees_in_your_city_or_neighbourhood_are_spiritual,
           agree_stressful = how_much_do_you_agree_that_the_trees_in_your_city_or_neighbourhood_make_me_feel_stressed,
           agree_healty = how_much_do_you_agree_that_the_trees_in_your_city_or_neighbourhood_make_me_feel_healthy,
           donate_family = how_many_canadian_dollars_should_the_following_donate_annually_to_urban_tree_programs_an_average_family,
           donate_individual = how_many_canadian_dollars_should_the_following_donate_annually_to_urban_tree_programs_yourself,
           knowledge_planting = please_rate_your_knowledge_of_planting_a_tree,
           knowledge_caring = please_rate_your_knowledge_of_caring_for_a_tree,
           knowledge_identifyingnativesp = please_rate_your_knowledge_of_identifying_trees_native_to_my_area,
           knowledge_treenames = please_rate_your_knowledge_of_knowing_the_names_of_everyday_trees,
           experience_havetree = do_you_have_a_tree_planted_in_front_of_your_home_house_residence_building,
           experience_plantedtree = have_you_planted_a_tree_in_the_past_five_years,
           experience_removetree = have_you_ever_contacted_your_city_to_prune_remove_replace_or_plant_trees,
           experience_feedback = have_you_ever_provided_your_city_with_feedback_regarding_urban_tree_policy_and_or_planning_via_a_public_consultation_or_engagement_e_g_city_town_meeting_open_house_online_postal_survey_etc,
           average_yardtime = in_average_over_a_year_how_many_hours_per_week_do_you_spend_in_your_yard_or_your_building_s_yard,
           average_parktime = in_average_over_a_year_how_many_hours_per_week_do_you_spend_in_public_green_areas_or_parks,
           satisfaction_typeloctree = how_satisfied_are_you_with_the_following_things_about_the_trees_in_your_city_or_neighbourhood_suitability_right_tree_for_the_location,
           satisfaction_attractiveness = how_satisfied_are_you_with_the_following_things_about_the_trees_in_your_city_or_neighbourhood_attractiveness_looks_good,
           satisfaction_risk = how_satisfied_are_you_with_the_following_things_about_the_trees_in_your_city_or_neighbourhood_safety_low_risk_of_damage_or_harm,
           satisfaction_quantity = how_satisfied_are_you_with_the_following_things_about_the_trees_in_your_city_or_neighbourhood_quantity_right_number_of_trees_for_area,
           satisfaction_nativeness = how_satisfied_are_you_with_the_following_things_about_the_trees_in_your_city_or_neighbourhood_nativeness_canadian_trees,
           satisfaction_exoticness = how_satisfied_are_you_with_the_following_things_about_the_trees_in_your_city_or_neighbourhood_exoticness_trees_from_overseas,
           satisfaction_diversity = how_satisfied_are_you_with_the_following_things_about_the_trees_in_your_city_or_neighbourhood_diversity_many_kinds_of_trees,
           satisfaction_habitat = how_satisfied_are_you_with_the_following_things_about_the_trees_in_your_city_or_neighbourhood_habitat_trees_that_provide_shelter_or_food_for_animals,
           satisfaction_timelyreplacement = how_satisfied_are_you_with_the_following_things_about_the_management_of_trees_in_your_city_or_neighbourhood_timely_replacement_of_trees_that_have_been_removed,
           satisfaction_removal = how_satisfied_are_you_with_the_following_things_about_the_management_of_trees_in_your_city_or_neighbourhood_removal_of_unhealthy_or_dead_trees,
           satisfaction_equity = how_satisfied_are_you_with_the_following_things_about_the_management_of_trees_in_your_city_or_neighbourhood_equitable_planting_of_trees_across_all_neighbourhoods_so_everybody_has_a_tree_near_them,
           satisfaction_responsiveness = how_satisfied_are_you_with_the_following_things_about_the_management_of_trees_in_your_city_or_neighbourhood_responsiveness_to_people_s_requests_to_prune_remove_replace_or_plant_trees,
           satisfaction_investment = how_satisfied_are_you_with_the_following_things_about_the_management_of_trees_in_your_city_or_neighbourhood_investment_in_tree_planting_and_caring,
           satisfaction_communityengagement = how_satisfied_are_you_with_the_following_things_about_the_management_of_trees_in_your_city_or_neighbourhood_engagement_with_the_community_on_decisions_related_to_public_trees,
           satisfaction_managementwateringpruning = how_satisfied_are_you_with_the_following_things_about_the_management_of_trees_in_your_city_or_neighbourhood_appropriate_management_of_living_trees_pruning_watering_etc,
           satisfaction_managementhabitat = how_satisfied_are_you_with_the_following_things_about_the_management_of_trees_in_your_city_or_neighbourhood_appropriate_management_of_living_trees_to_provide_habitat_for_wildlife_hollows_etc,
           governance_allowspublicinfluence = how_much_do_you_agree_with_the_following_statements_that_the_local_government_managing_trees_in_your_city_or_neighbourhood_allows_the_public_to_influence_the_outcome_of_decisions_that_are_made,
           governance_listenstopublic = how_much_do_you_agree_with_the_following_statements_that_the_local_government_managing_trees_in_your_city_or_neighbourhood_listens_to_the_public,
           governance_truthfulness = how_much_do_you_agree_with_the_following_statements_that_the_local_government_managing_trees_in_your_city_or_neighbourhood_is_truthful_with_the_public,
           governance_rightdecision = how_much_do_you_agree_with_the_following_statements_about_your_local_government_i_expect_that_the_local_government_will_make_the_right_decision_regarding_trees,
           governance_goodjob = how_much_do_you_agree_with_the_following_statements_about_your_local_government_i_am_confident_that_the_local_government_will_do_a_good_job_managing_trees,
           governance_trustworthiness = how_much_do_you_agree_with_the_following_statements_about_your_local_government_i_trust_the_local_government_to_take_responsibility_for_managing_trees,
           neighbourhood_helpfulness = thinking_about_the_life_in_your_neighbourhood_how_do_you_agree_with_the_following_statements_people_around_here_are_willing_to_help_their_neighbors,
           neighbourhood_closeness = thinking_about_the_life_in_your_neighbourhood_how_do_you_agree_with_the_following_statements_this_is_a_close_knit_neighborhood,
           neighbourhood_trustworthiness = thinking_about_the_life_in_your_neighbourhood_how_do_you_agree_with_the_following_statements_people_in_this_neighborhood_can_be_trusted,
           neighbourhood_dontgetalong = thinking_about_the_life_in_your_neighbourhood_how_do_you_agree_with_the_following_statements_people_in_this_neighborhood_generally_don_t_get_along_with_each_other,
           neighbourhood_differingvalues = thinking_about_the_life_in_your_neighbourhood_how_do_you_agree_with_the_following_statements_people_in_this_neighborhood_do_not_share_the_same_values,
           rate_remotewildernessvacation = please_rate_the_extent_to_which_you_agree_with_each_statement_please_respond_as_you_really_feel_rather_than_how_you_think_most_people_feel_my_ideal_vacation_spot_would_be_a_remote_wilderness_area,
           rate_personalactionsenvironment = please_rate_the_extent_to_which_you_agree_with_each_statement_please_respond_as_you_really_feel_rather_than_how_you_think_most_people_feel_i_always_think_about_how_my_actions_affect_the_environment,
           rate_naturespirtual = please_rate_the_extent_to_which_you_agree_with_each_statement_please_respond_as_you_really_feel_rather_than_how_you_think_most_people_feel_my_connection_to_nature_and_the_environment_is_a_part_of_my_spirituality,
           rate_noticewildlife = please_rate_the_extent_to_which_you_agree_with_each_statement_please_respond_as_you_really_feel_rather_than_how_you_think_most_people_feel_i_take_notice_of_wildlife_wherever_i_am,
           rate_natureimportance = please_rate_the_extent_to_which_you_agree_with_each_statement_please_respond_as_you_really_feel_rather_than_how_you_think_most_people_feel_my_connection_to_nature_is_an_important_part_of_who_i_am,
           rate_eartheconnection = please_rate_the_extent_to_which_you_agree_with_each_statement_please_respond_as_you_really_feel_rather_than_how_you_think_most_people_feel_i_fell_very_connected_to_all_living_things_and_the_earth,
           personalsat_standardliving = thinking_about_your_own_life_and_personal_circumstances_how_satisfied_are_you_with_your_standard_of_living,
           personalsat_health = thinking_about_your_own_life_and_personal_circumstances_how_satisfied_are_you_with_your_health,
           personalsat_achievement = thinking_about_your_own_life_and_personal_circumstances_how_satisfied_are_you_with_what_you_are_currently_achieving_in_life,
           personalsat_relationships = thinking_about_your_own_life_and_personal_circumstances_how_satisfied_are_you_with_your_personal_relationships,
           personalsat_safety = thinking_about_your_own_life_and_personal_circumstances_how_satisfied_are_you_with_how_safe_you_feel,
           personalsat_community = thinking_about_your_own_life_and_personal_circumstances_how_satisfied_are_you_with_your_feeling_part_of_your_community,
           personalsat_futuresecurity = thinking_about_your_own_life_and_personal_circumstances_how_satisfied_are_you_with_your_future_security,
           personalsat_life = thinking_about_your_own_life_and_personal_circumstances_how_satisfied_are_you_with_your_life_as_a_whole,
           length_neighbourhood = how_long_have_you_lived_in_your_current_neighborhoood_type_number_of_years_leave_blank_if_you_don_t_know_or_prefer_not_to_answer,
           length_urban = how_long_have_you_lived_in_urban_areas_type_number_of_years_leave_blank_if_you_don_t_know_or_prefer_not_to_answer,
           length_rural = how_long_have_you_lived_in_rural_areas_type_number_of_years_leave_blank_if_you_don_t_know_or_prefer_not_to_answer,
           housing_choice = what_is_your_housing_situation_selected_choice,
           housing_other = what_is_your_housing_situation_other_define_if_you_want_text,
           dwelling_choice = what_type_of_dwelling_do_you_live_in_selected_choice,
           dwelling_other = what_type_of_dwelling_do_you_live_in_other_define_if_you_want_text,
           canadaborn = were_you_born_in_canada,
           year_arrival_choice = what_year_did_you_come_to_canada_selected_choice,
           year_arrival_other = what_year_did_you_come_to_canada_please_type_the_exact_or_approximate_year_text,
           canadabornparents = were_your_parents_born_in_canada,
           language_choice = do_you_speak_any_other_language_other_than_english_with_your_family_at_home_selected_choice,
           language_other = do_you_speak_any_other_language_other_than_english_with_your_family_at_home_yes_please_type_type_which_text,
           birthdecade = in_which_decade_were_you_born,
           education = what_is_your_highest_educational_degree_awarded,
           envorg = do_you_belong_to_an_environmental_organization,
           ethnicity_choice = what_ethnicity_do_you_identify_with_select_as_many_as_apply_selected_choice,
           ethnicity_other = what_ethnicity_do_you_identify_with_select_as_many_as_apply_other_please_specify_if_you_want_text,
           gender_choice = what_gender_do_you_identify_with_selected_choice,
           gender_other = what_gender_do_you_identify_with_other_define_if_you_want_text,
           postcode_choice = what_is_your_postcode_selected_choice,
           postcode_other = what_is_your_postcode_please_type_either_the_first_3_digits_or_the_full_6_digits_text)
  
  
  mtl_eng_filt <- mtl_eng_rcols %>%
    # remove undesirable response types
    filter(finished == "True",
           eighteen == "Yes",
           !municipality %in% c("Dorval", "Blainville", "Oka", "None of the above/ other"), # dummy cities,
           response_type != "Spam",
           !if_all(importance_largeoldtrees:personalsat_life, is.na)) %>%
    # classify inner, middle, and outer region responses
    mutate(region = case_when(
      municipality %in% "Montreal" == T ~ "inner",
      municipality %in% c("Laval", "Lac-Saint-Louis district (e.g., Point Claire, Beaconsfield)", "Longueuil", "Vaudreuil-Soulanges") == T ~ "middle",
      municipality %in% c("Châteauguay-Lacolle", "Montarville", "Terrebonne") == T ~ "outer",
      municipality %in% c("Joliette", "Saint-Hyacinthe-Bagot", "Saint-Jean", "Argenteuil-La Petite-Nation") == T ~ "regional"
    ))
  
  
  mtl_eng_sel <- mtl_eng_filt %>%
    select(start_date, response_type, ip_address, response_id, location_latitude, location_longitude, user_language,
           municipality, region, postcode_other, importance_largeoldtrees, importance_historystories, importance_stressrelief, importance_walks, 
           importance_culturaltraditions, importance_accessiblespace, importance_cleanairwatercity, importance_nativespecies,
           importance_welcoming, importance_liveability, importance_socializing, importance_communitycohesion, importance_beauty,
           importance_cleanenvsupportingppl, importance_attractingpeople, importance_maintainculture,
           agree_allergies, agree_blockroadsigns, agree_damageproperty, agree_messy, agree_ugly, agree_toomuchwater, agree_blockpipes,
           agree_blocksun, agree_expensive, agree_dropbranches, agree_toomuchspace, agree_wildfires, agree_undesirableanimals, 
           agree_desirableanimals, agree_screenbadviews, agree_createsafety, agree_calming, agree_cleanair, agree_provideshade,
           agree_produceoxygen, agree_cooling, agree_reducefloods, agree_goodexercise, agree_goodshopping, agree_incpropertyvalues, 
           agree_spiritual, agree_stressful, agree_healty, donate_family, donate_individual, knowledge_planting, knowledge_caring,
           knowledge_identifyingnativesp, knowledge_treenames, experience_havetree, experience_plantedtree, experience_removetree,
           experience_feedback, average_yardtime, average_parktime, satisfaction_typeloctree, satisfaction_attractiveness, 
           satisfaction_risk, satisfaction_quantity, satisfaction_nativeness, satisfaction_exoticness, satisfaction_diversity,
           satisfaction_habitat, satisfaction_timelyreplacement, satisfaction_removal, satisfaction_equity, satisfaction_responsiveness,
           satisfaction_investment, satisfaction_communityengagement, satisfaction_managementwateringpruning, satisfaction_managementhabitat,
           governance_allowspublicinfluence, governance_listenstopublic, governance_truthfulness, governance_rightdecision,
           governance_goodjob, governance_trustworthiness, neighbourhood_helpfulness, neighbourhood_closeness, neighbourhood_trustworthiness,
           neighbourhood_dontgetalong, neighbourhood_differingvalues, rate_remotewildernessvacation, rate_personalactionsenvironment, rate_naturespirtual,
           rate_noticewildlife, rate_natureimportance, rate_eartheconnection, personalsat_standardliving, personalsat_health, personalsat_achievement,
           personalsat_relationships, personalsat_safety, personalsat_community, personalsat_futuresecurity, personalsat_life, length_neighbourhood,
           length_urban, length_rural, housing_choice, housing_other, dwelling_choice, dwelling_other, canadaborn, year_arrival_other, canadabornparents,
           language_other, birthdecade, education, envorg, ethnicity_choice, ethnicity_other, gender_choice, gender_other)
  
  return(mtl_eng_sel)
  
  
  
}