clean_mtl_fre <- function(mtl_fr_raw){
  
  # clean column names 
  mtl_fr_cols <- clean_names(mtl_fr_raw)
  
  # rename columns
  mtl_fr_rcols <- mtl_fr_cols %>% 
    rename(eighteen = avez_vous_18_ans_ou_plus,
           municipality = dans_quel_quartier_ou_quelle_municipalite_habitez_vous_veuillez_selectionner_la_commune_et_non_votre_quartier_ou_votre_region,
           importance_largeoldtrees = quelle_est_l_importance_pour_vous_de_chacune_des_choses_suivantes_concernant_ces_arbres_de_grands_vieux_arbres,
           importance_historystories = quelle_est_l_importance_pour_vous_de_chacune_des_choses_suivantes_concernant_ces_arbres_un_lieu_d_histoires_humaines_et_d_histoire,
           importance_stressrelief = quelle_est_l_importance_pour_vous_de_chacune_des_choses_suivantes_concernant_ces_arbres_s_evader_du_stress_de_la_vie_quotidienne,
           importance_walks = quelle_est_l_importance_pour_vous_de_chacune_des_choses_suivantes_concernant_ces_arbres_un_lieu_pour_une_courte_marche,
           importance_culturaltraditions = quelle_est_l_importance_pour_vous_de_chacune_des_choses_suivantes_concernant_ces_arbres_apprendre_sur_les_traditions_culturelles,
           importance_accessiblespace = quelle_est_l_importance_pour_vous_de_chacune_des_choses_suivantes_concernant_ces_arbres_un_lieu_qui_est_accessible_a_tous_et_toutes,
           importance_cleanairwatercity = quelle_est_l_importance_pour_vous_de_chacune_des_choses_suivantes_concernant_ces_arbres_air_propre_eau_propre_et_villes_saines,
           importance_nativespecies = quelle_est_l_importance_pour_vous_de_chacune_des_choses_suivantes_concernant_ces_arbres_plusieurs_types_d_animaux_d_oiseaux_et_de_plantes_indigenes,
           importance_welcoming = quelle_est_l_importance_pour_vous_de_chacune_des_choses_suivantes_concernant_ces_arbres_rendre_la_ville_plus_accueillante,
           importance_liveability = quelle_est_l_importance_pour_vous_de_chacune_des_choses_suivantes_concernant_ces_arbres_une_ville_plus_vivable,
           importance_socializing = quelle_est_l_importance_pour_vous_de_chacune_des_choses_suivantes_concernant_ces_arbres_espaces_pour_les_gens_pour_interagir_et_socialiser,
           importance_communitycohesion = quelle_est_l_importance_pour_vous_de_chacune_des_choses_suivantes_concernant_ces_arbres_ameliorer_la_cohesion_communautaire,
           importance_beauty = quelle_est_l_importance_pour_vous_de_chacune_des_choses_suivantes_concernant_ces_arbres_belles_vues_sons_et_odeurs,
           importance_cleanenvsupportingppl = quelle_est_l_importance_pour_vous_de_chacune_des_choses_suivantes_concernant_ces_arbres_un_environnement_sain_qui_supporte_la_vie_humaine,
           importance_attractingpeople = quelle_est_l_importance_pour_vous_de_chacune_des_choses_suivantes_concernant_ces_arbres_attirer_des_touristes_et_des_residents_a_la_ville,
           importance_maintainculture = quelle_est_l_importance_pour_vous_de_chacune_des_choses_suivantes_concernant_ces_arbres_maintenir_les_cultures_autochtones_ou_europeennes,
           agree_allergies = dans_quelles_mesures_etes_vous_d_accord_que_les_arbres_dans_votre_municipalite_causent_des_allergies,
           agree_blockroadsigns = dans_quelles_mesures_etes_vous_d_accord_que_les_arbres_dans_votre_municipalite_bloquent_la_visibilite_des_panneaux_routiers,
           agree_damageproperty = dans_quelles_mesures_etes_vous_d_accord_que_les_arbres_dans_votre_municipalite_endommagent_les_proprietes_incluant_les_sentiers_de_beton_et_les_lignes_electriques,
           agree_messy = dans_quelles_mesures_etes_vous_d_accord_que_les_arbres_dans_votre_municipalite_creent_un_desordre,
           agree_ugly = dans_quelles_mesures_etes_vous_d_accord_que_les_arbres_dans_votre_municipalite_sont_laids,
           agree_toomuchwater = dans_quelles_mesures_etes_vous_d_accord_que_les_arbres_dans_votre_municipalite_utilisent_trop_d_eau,
           agree_blockpipes = dans_quelles_mesures_etes_vous_d_accord_que_les_arbres_dans_votre_municipalite_bloquent_les_conduites_d_eau_et_les_drains,
           agree_blocksun = dans_quelles_mesures_etes_vous_d_accord_que_les_arbres_dans_votre_municipalite_bloquent_le_soleil,
           agree_expensive = dans_quelles_mesures_etes_vous_d_accord_que_les_arbres_dans_votre_municipalite_sont_couteux_a_entretenir,
           agree_dropbranches = dans_quelles_mesures_etes_vous_d_accord_que_les_arbres_dans_votre_municipalite_perdent_des_branches,
           agree_toomuchspace = dans_quelles_mesures_etes_vous_d_accord_que_les_arbres_dans_votre_municipalite_prennent_trop_d_espace,
           agree_wildfires = dans_quelles_mesures_etes_vous_d_accord_que_les_arbres_dans_votre_municipalite_favorisent_les_feux_de_forets,
           agree_undesirableanimals = dans_quelles_mesures_etes_vous_d_accord_que_les_arbres_dans_votre_municipalite_attirent_des_animaux_indesirables,
           agree_desirableanimals = dans_quelles_mesures_etes_vous_d_accord_que_les_arbres_dans_votre_municipalite_attirent_des_animaux_desirables,
           agree_screenbadviews = dans_quelles_mesures_etes_vous_d_accord_que_les_arbres_dans_votre_municipalite_bloquent_des_vues_peu_attrayantes,
           agree_createsafety = dans_quelles_mesures_etes_vous_d_accord_que_les_arbres_dans_votre_municipalite_rendre_les_rues_et_les_parcs_plus_surs,
           agree_calming = dans_quelles_mesures_etes_vous_d_accord_que_les_arbres_dans_votre_municipalite_sont_calmants,
           agree_cleanair = dans_quelles_mesures_etes_vous_d_accord_que_les_arbres_dans_votre_municipalite_purifient_l_air,
           agree_provideshade = dans_quelles_mesures_etes_vous_d_accord_que_les_arbres_dans_votre_municipalite_fournissent_de_l_ombre,
           agree_produceoxygen = dans_quelles_mesures_etes_vous_d_accord_que_les_arbres_dans_votre_municipalite_produisent_de_l_oxygene,
           agree_cooling = dans_quelles_mesures_etes_vous_d_accord_que_les_arbres_dans_votre_municipalite_refroidir_le_quartier,
           agree_reducefloods = dans_quelles_mesures_etes_vous_d_accord_que_les_arbres_dans_votre_municipalite_reduisent_les_inondations,
           agree_goodexercise = dans_quelles_mesures_etes_vous_d_accord_que_les_arbres_dans_votre_municipalite_creer_un_endroit_propice_a_l_exercice_marcher_courir_faire_du_velo,
           agree_goodshopping = dans_quelles_mesures_etes_vous_d_accord_que_les_arbres_dans_votre_municipalite_sont_un_bon_endroit_pour_magasiner,
           agree_incpropertyvalues = dans_quelles_mesures_etes_vous_d_accord_que_les_arbres_dans_votre_municipalite_augmentent_la_valeur_des_proprietes,
           agree_spiritual = dans_quelles_mesures_etes_vous_d_accord_que_les_arbres_dans_votre_municipalite_sont_spirituels,
           agree_stressful = dans_quelles_mesures_etes_vous_d_accord_que_les_arbres_dans_votre_municipalite_me_font_sentir_stresse_e,
           agree_healty = dans_quelles_mesures_etes_vous_d_accord_que_les_arbres_dans_votre_municipalite_me_font_sentir_en_bonne_sante,
           donate_family = en_sommes_d_argents_canadiens_combien_attendez_vous_a_ce_qu_un_des_groupes_suivants_devraient_verser_annuellement_aux_programmes_de_foresterie_urbaine_une_famille_de_classe_moyenne,
           donate_individual = en_sommes_d_argents_canadiens_combien_attendez_vous_a_ce_qu_un_des_groupes_suivants_devraient_verser_annuellement_aux_programmes_de_foresterie_urbaine_vous_meme,
           knowledge_planting = valuez_vos_connaissances_sur_les_suivant_planter_un_arbre,
           knowledge_caring = valuez_vos_connaissances_sur_les_suivant_prendre_soin_d_un_arbre,
           knowledge_identifyingnativesp = valuez_vos_connaissances_sur_les_suivant_identifier_des_arbres_indigenes_de_ma_region,
           knowledge_treenames = valuez_vos_connaissances_sur_les_suivant_connaitre_les_noms_des_arbres_communs,
           experience_havetree = avez_vous_un_arbre_plante_devant_votre_residence_maison_residence_edifice,
           experience_plantedtree = avez_vous_plante_un_arbre_dans_les_cinq_dernieres_annees,
           experience_removetree = avez_vous_deja_contacte_votre_ville_pour_tailler_abattre_ou_planter_un_arbre,
           experience_feedback = avez_vous_deja_fourni_a_votre_ville_des_commentaires_concernant_la_politique_et_ou_la_planification_des_arbres_urbains_via_une_consultation_ou_un_engagement_public_par_exemple_une_reunion_municipale_une_journee_portes_ouvertes_un_sondage_en_ligne_postal_etc,
           average_yardtime = sur_une_periode_d_une_annee_combien_de_temps_passez_vous_en_moyenne_par_semaine_dans_votre_cour_ou_la_cour_de_votre_edifice,
           average_parktime = sur_une_periode_d_une_annee_combien_de_temps_passez_vous_en_moyenne_par_semaine_dans_des_espaces_vert_publics_ou_des_parcs,
           satisfaction_typeloctree = dans_quelles_mesures_etes_vous_satisfait_des_aspects_suivants_concernant_les_arbres_de_votre_municipalite_pertinence_arbre_propice_pour_le_lieu,
           satisfaction_attractiveness = dans_quelles_mesures_etes_vous_satisfait_des_aspects_suivants_concernant_les_arbres_de_votre_municipalite_attractivite_pour_l_esthetique,
           satisfaction_risk = dans_quelles_mesures_etes_vous_satisfait_des_aspects_suivants_concernant_les_arbres_de_votre_municipalite_securite_faible_risque_de_dommage_ou_blessure,
           satisfaction_quantity = dans_quelles_mesures_etes_vous_satisfait_des_aspects_suivants_concernant_les_arbres_de_votre_municipalite_quantite_nombre_approprie_d_arbres_pour_l_espace,
           satisfaction_nativeness = dans_quelles_mesures_etes_vous_satisfait_des_aspects_suivants_concernant_les_arbres_de_votre_municipalite_indigene_arbres_canadiens,
           satisfaction_exoticness = dans_quelles_mesures_etes_vous_satisfait_des_aspects_suivants_concernant_les_arbres_de_votre_municipalite_exotisme_arbres_de_provenance_etrangere,
           satisfaction_diversity = dans_quelles_mesures_etes_vous_satisfait_des_aspects_suivants_concernant_les_arbres_de_votre_municipalite_diversite_plusieurs_especes_d_arbres,
           satisfaction_habitat = dans_quelles_mesures_etes_vous_satisfait_des_aspects_suivants_concernant_les_arbres_de_votre_municipalite_habitat_arbres_qui_fournissent_un_abri_ou_de_la_nourriture_pour_les_animaux,
           satisfaction_timelyreplacement = dans_quelles_mesures_etes_vous_satisfait_avec_les_aspects_suivants_concernant_la_gestion_des_arbres_de_votre_municipalite_remplacement_rapide_des_arbres_qui_ont_ete_abattus,
           satisfaction_removal = dans_quelles_mesures_etes_vous_satisfait_avec_les_aspects_suivants_concernant_la_gestion_des_arbres_de_votre_municipalite_enlevement_d_arbres_malades_ou_morts,
           satisfaction_equity = dans_quelles_mesures_etes_vous_satisfait_avec_les_aspects_suivants_concernant_la_gestion_des_arbres_de_votre_municipalite_plantation_equitable_d_arbres_dans_tous_les_quartiers_afin_que_chacun_ait_un_arbre_pres_de_chez_lui,
           satisfaction_responsiveness = dans_quelles_mesures_etes_vous_satisfait_avec_les_aspects_suivants_concernant_la_gestion_des_arbres_de_votre_municipalite_reaction_aux_demandes_des_gens_pour_tailler_abattre_remplacer_ou_planter_des_arbres,
           satisfaction_investment = dans_quelles_mesures_etes_vous_satisfait_avec_les_aspects_suivants_concernant_la_gestion_des_arbres_de_votre_municipalite_investissement_pour_la_plantation_et_le_soin_d_arbres,
           satisfaction_communityengagement = dans_quelles_mesures_etes_vous_satisfait_avec_les_aspects_suivants_concernant_la_gestion_des_arbres_de_votre_municipalite_engagement_avec_la_communaute_sur_les_decisions_reliees_aux_arbres_publics,
           satisfaction_managementwateringpruning = dans_quelles_mesures_etes_vous_satisfait_avec_les_aspects_suivants_concernant_la_gestion_des_arbres_de_votre_municipalite_gestion_appropriee_des_arbres_tailler_arroser_etc,
           satisfaction_managementhabitat = dans_quelles_mesures_etes_vous_satisfait_avec_les_aspects_suivants_concernant_la_gestion_des_arbres_de_votre_municipalite_gestion_appropriee_des_arbres_pour_fournir_un_habitat_a_la_faune_et_la_flore_creuser_etc,
           governance_allowspublicinfluence = dans_quelles_mesures_etes_vous_d_accord_avec_les_enonces_suivantes_concernant_la_gestion_des_arbres_dans_votre_municipalite_par_votre_gouvernement_local_permet_au_public_d_influencer_le_resultat_des_decisions_qui_sont_prises,
           governance_listenstopublic = dans_quelles_mesures_etes_vous_d_accord_avec_les_enonces_suivantes_concernant_la_gestion_des_arbres_dans_votre_municipalite_par_votre_gouvernement_local_est_a_l_ecoute_du_public,
           governance_truthfulness = dans_quelles_mesures_etes_vous_d_accord_avec_les_enonces_suivantes_concernant_la_gestion_des_arbres_dans_votre_municipalite_par_votre_gouvernement_local_est_honnete_avec_le_public,
           governance_rightdecision = dans_quelles_mesures_etes_vous_d_accord_avec_les_declarations_suivantes_concernant_votre_gouvernement_municipal_je_m_attends_a_ce_que_le_gouvernement_municipal_prenne_la_bonne_decision_concernant_les_arbres,
           governance_goodjob = dans_quelles_mesures_etes_vous_d_accord_avec_les_declarations_suivantes_concernant_votre_gouvernement_municipal_je_suis_confiant_que_le_gouvernement_municipal_fera_un_bon_travail_quant_a_la_gestion_des_arbres,
           governance_trustworthiness = dans_quelles_mesures_etes_vous_d_accord_avec_les_declarations_suivantes_concernant_votre_gouvernement_municipal_je_fais_confiance_au_gouvernement_municipal_pour_prendre_la_responsabilite_de_la_gestion_des_arbres,
           neighbourhood_helpfulness = dans_quelle_mesure_etes_vous_d_accord_avec_les_enonces_suivants_au_sujet_de_la_vie_de_votre_quartier_les_gens_d_ici_sont_prets_a_aider_leurs_voisins,
           neighbourhood_closeness = dans_quelle_mesure_etes_vous_d_accord_avec_les_enonces_suivants_au_sujet_de_la_vie_de_votre_quartier_c_est_un_quartier_tres_uni,
           neighbourhood_trustworthiness = dans_quelle_mesure_etes_vous_d_accord_avec_les_enonces_suivants_au_sujet_de_la_vie_de_votre_quartier_on_peut_faire_confiance_aux_gens_de_ce_quartier,
           neighbourhood_dontgetalong = dans_quelle_mesure_etes_vous_d_accord_avec_les_enonces_suivants_au_sujet_de_la_vie_de_votre_quartier_les_gens_de_ce_quartier_ne_s_entendent_generalement_pas_bien,
           neighbourhood_differingvalues = dans_quelle_mesure_etes_vous_d_accord_avec_les_enonces_suivants_au_sujet_de_la_vie_de_votre_quartier_les_gens_de_ce_quartier_ne_partagent_pas_les_memes_valeurs,
           rate_remotewildernessvacation = evaluer_dans_quelles_mesures_vous_etes_d_accord_avec_chaque_declaration_repondez_ce_que_vous_ressentez_veritablement_plutot_que_du_statu_quo_mon_lieu_de_vacances_ideal_serait_une_region_isolee_dans_la_nature,
           rate_personalactionsenvironment = evaluer_dans_quelles_mesures_vous_etes_d_accord_avec_chaque_declaration_repondez_ce_que_vous_ressentez_veritablement_plutot_que_du_statu_quo_je_pense_toujours_comment_mes_actions_affectent_l_environnement,
           rate_naturespirtual = evaluer_dans_quelles_mesures_vous_etes_d_accord_avec_chaque_declaration_repondez_ce_que_vous_ressentez_veritablement_plutot_que_du_statu_quo_ma_connexion_avec_la_nature_et_l_environnement_fait_partie_de_ma_spiritualite,
           rate_noticewildlife = evaluer_dans_quelles_mesures_vous_etes_d_accord_avec_chaque_declaration_repondez_ce_que_vous_ressentez_veritablement_plutot_que_du_statu_quo_je_remarque_toute_faune_sauvage_peu_importe_ou_je_suis,
           rate_natureimportance = evaluer_dans_quelles_mesures_vous_etes_d_accord_avec_chaque_declaration_repondez_ce_que_vous_ressentez_veritablement_plutot_que_du_statu_quo_mon_lien_avec_la_nature_est_une_partie_importante_de_ma_personnalite,
           rate_eartheconnection = evaluer_dans_quelles_mesures_vous_etes_d_accord_avec_chaque_declaration_repondez_ce_que_vous_ressentez_veritablement_plutot_que_du_statu_quo_je_me_sens_lie_a_tous_les_etres_vivants_ainsi_qu_a_la_terre,
           personalsat_standardliving = en_prenant_compte_de_votre_vie_et_vos_circonstances_personnelles_dans_quelle_mesure_etes_vous_satisfait_avec_votre_niveau_de_vie,
           personalsat_health = en_prenant_compte_de_votre_vie_et_vos_circonstances_personnelles_dans_quelle_mesure_etes_vous_satisfait_avec_votre_sante,
           personalsat_achievement = en_prenant_compte_de_votre_vie_et_vos_circonstances_personnelles_dans_quelle_mesure_etes_vous_satisfait_avec_ce_que_vous_accomplissez_actuellement_dans_votre_vie,
           personalsat_relationships = en_prenant_compte_de_votre_vie_et_vos_circonstances_personnelles_dans_quelle_mesure_etes_vous_satisfait_avec_vos_relations_personnelles,
           personalsat_safety = en_prenant_compte_de_votre_vie_et_vos_circonstances_personnelles_dans_quelle_mesure_etes_vous_satisfait_avec_comment_vous_vous_sentez_en_securite,
           personalsat_community = en_prenant_compte_de_votre_vie_et_vos_circonstances_personnelles_dans_quelle_mesure_etes_vous_satisfait_avec_votre_sentiment_d_appartenance_a_la_communaute,
           personalsat_futuresecurity = en_prenant_compte_de_votre_vie_et_vos_circonstances_personnelles_dans_quelle_mesure_etes_vous_satisfait_avec_votre_securite_future,
           personalsat_life = en_prenant_compte_de_votre_vie_et_vos_circonstances_personnelles_dans_quelle_mesure_etes_vous_satisfait_avec_votre_vie_dans_son_ensemble,
           length_neighbourhood = depuis_combien_d_annees_habitez_vous_dans_votre_municipalite_ecrivez_le_nombre_d_annees_laissez_vide_si_vous_ne_savez_pas_ou_si_vous_preferez_ne_pas_repondre,
           length_urban = depuis_combien_d_annees_habitez_vous_dans_des_zones_urbaines_ecrivez_le_nombre_d_annees_laissez_vide_si_vous_ne_savez_pas_ou_si_vous_preferez_ne_pas_repondre,
           length_rural = depuis_combien_d_annees_habitez_vous_dans_des_endroits_ruraux_ecrivez_le_nombre_d_annees_laissez_vide_si_vous_ne_savez_pas_ou_si_vous_preferez_ne_pas_repondre,
           housing_choice = quelle_est_votre_situation_en_terme_de_logement_selected_choice,
           housing_other = quelle_est_votre_situation_en_terme_de_logement_autre_definir_si_vous_voulez_text,
           dwelling_choice = dans_quel_type_de_logement_habitez_vous_selected_choice,
           dwelling_other = dans_quel_type_de_logement_habitez_vous_autre_definir_si_vous_voulez_text,
           canadaborn = etes_vous_ne_e_au_canada,
           year_arrival_choice = en_quelle_annee_etes_vous_arrive_e_au_canada_selected_choice,
           year_arrival_other = en_quelle_annee_etes_vous_arrive_e_au_canada_veuillez_ecrire_l_annee_exacte_ou_approximative_text,
           canadabornparents = vos_parents_sont_ils_nes_au_canada,
           language_choice = parlez_vous_une_autre_langue_autre_que_l_anglais_avec_votre_famille_a_la_maison_selected_choice,
           language_other = parlez_vous_une_autre_langue_autre_que_l_anglais_avec_votre_famille_a_la_maison_oui_veuillez_ecrire_laquelle_lesquelles_text,
           birthdecade = dans_quelle_decennie_etes_vous_ne_e,
           education = quel_est_votre_niveau_de_scolarite_le_plus_eleve,
           envorg = etes_vous_membre_d_une_organisation_environnementale,
           ethnicity_choice = a_quelle_ethnicite_identifiez_vous_selectionnez_ceux_ou_celles_qui_s_appliquent_selected_choice,
           ethnicity_other = a_quelle_ethnicite_identifiez_vous_selectionnez_ceux_ou_celles_qui_s_appliquent_autre_s_il_vous_plait_specifiez_si_vous_voulez_text,
           gender_choice = a_quel_genre_identifiez_vous_selected_choice,
           gender_other = a_quel_genre_identifiez_vous_autre_definir_si_vous_voulez_text,
           postcode_choice = quel_est_votre_code_postal_selected_choice,
           postcode_other = quel_est_votre_code_postal_please_type_either_the_first_3_digits_or_the_full_6_digits_text)
  
  
  mtl_fr_filt <- mtl_fr_rcols %>%
    # remove undesirable response types
    filter(finished == "True",
           eighteen == "Oui",
           !municipality %in% c("Dorval", "Blainville", "Oka", "Aucune des réponses ci-dessus / autre"), # dummy cities,
           response_type != "Spam",
           !if_all(importance_largeoldtrees:personalsat_life, is.na)) %>%
    # classify inner, middle, and outer region responses
    mutate(region = case_when(
      municipality %in% "Montreal" == T ~ "inner",
      municipality %in% c("Laval", "Lac-Saint-Louis district (e.g., Point Claire, Beaconsfield)", "Longueuil", "Vaudreuil-Soulanges") == T ~ "middle",
      municipality %in% c("Châteauguay-Lacolle", "Montarville", "Terrebonne") == T ~ "outer",
      municipality %in% c("Joliette", "Saint-Hyacinthe-Bagot", "Saint-Jean", "Argenteuil-La Petite-Nation") == T ~ "regional"
    ),
    user_language = "FR")
  
  
  mtl_fr_sel <- mtl_fr_filt %>%
    select(start_date, response_type, ip_address, sesskey, response_id, location_latitude, location_longitude, user_language,
           municipality, region, postcode_other, importance_largeoldtrees, importance_historystories, importance_stressrelief, importance_walks, 
           importance_culturaltraditions, importance_accessiblespace, importance_cleanairwatercity, importance_nativespecies,
           importance_welcoming, importance_liveability, importance_socializing, importance_communitycohesion, importance_beauty,
           importance_cleanenvsupportingppl, importance_attractingpeople, importance_maintainculture,
           agree_allergies, agree_blockroadsigns, agree_damageproperty, agree_messy, agree_ugly, agree_toomuchwater, agree_blockpipes,
           agree_blocksun, agree_expensive, agree_dropbranches, agree_toomuchspace, agree_wildfires, agree_undesirableanimals, 
           agree_desirableanimals, agree_screenbadviews, agree_createsafety, agree_calming, agree_cleanair, agree_provideshade,
           agree_produceoxygen, agree_cooling, agree_reducefloods, agree_goodexercise, agree_goodshopping, agree_incpropertyvalues, 
           agree_spiritual, agree_stressful, agree_healty, donate_family, donate_individual, knowledge_planting, knowledge_caring,
           knowledge_identifyingnativesp, knowledge_treenames, experience_havetree, experience_plantedtree, experience_removetree,
           experience_feedback, average_yardtime, average_parktime, satisfaction_typeloctree, satisfaction_attractiveness, 
           satisfaction_risk, satisfaction_quantity, satisfaction_nativeness, satisfaction_exoticness, satisfaction_diversity,
           satisfaction_habitat, satisfaction_timelyreplacement, satisfaction_removal, satisfaction_equity, satisfaction_responsiveness,
           satisfaction_investment, satisfaction_communityengagement, satisfaction_managementwateringpruning, satisfaction_managementhabitat,
           governance_allowspublicinfluence, governance_listenstopublic, governance_truthfulness, governance_rightdecision,
           governance_goodjob, governance_trustworthiness, neighbourhood_helpfulness, neighbourhood_closeness, neighbourhood_trustworthiness,
           neighbourhood_dontgetalong, neighbourhood_differingvalues, rate_remotewildernessvacation, rate_personalactionsenvironment, rate_naturespirtual,
           rate_noticewildlife, rate_natureimportance, rate_eartheconnection, personalsat_standardliving, personalsat_health, personalsat_achievement,
           personalsat_relationships, personalsat_safety, personalsat_community, personalsat_futuresecurity, personalsat_life, length_neighbourhood,
           length_urban, length_rural, housing_choice, housing_other, dwelling_choice, dwelling_other, canadaborn, year_arrival_other, canadabornparents,
           language_other, birthdecade, education, envorg, ethnicity_choice, ethnicity_other, gender_choice, gender_other)
  
  return(mtl_fr_sel)
}